version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - DB_HOST=${MONGO_HOST}
      - DB_PORT=${MONGO_PORT}
      - DB_USER=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PASSWORD}
      - DATABASE=${MONGO_DATABASE}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


volumes:
  mongodb_data:
