version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://appuser:apppassword@mongo:27017/mongobd
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mongobd
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: